"""Create task table

Revision ID: 5e46b69bd4d2
Revises: 02d25e5adcad
Create Date: 2024-08-30 16:06:40.744933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e46b69bd4d2'
down_revision = '02d25e5adcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('path_config', sa.JSON(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('review_started_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
