"""alter_display_config_table

Revision ID: 8e7862076451
Revises: 92cc7dc98d4d
Create Date: 2024-09-05 15:27:53.792161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7862076451'
down_revision = '92cc7dc98d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('user_email')
        batch_op.drop_column('case_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_timestamp')

    # ### end Alembic commands ###
