"""remove case id from answer

Revision ID: b3708f6bc9fd
Revises: 8e7862076451
Create Date: 2024-09-06 10:23:58.797758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3708f6bc9fd'
down_revision = '8e7862076451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('case_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
